### ISSUE TITLE
Device lost looping when try to recompile shaders

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#12]
I loaded HUGE scene [BistroExterior.gltf](https://drive.google.com/file/d/1g58-OA9TkTgkGd6lO4H4PeqmJcxUUuuz/view?usp=drive_link) and all rendered ok.
When I press ctrl-R to recompile shaders I have error
![dev-lost](https://github.com/user-attachments/assets/03f7b479-3286-4da9-92f5-16aefebb3c8b)

And program looped and failed.

I use Windows 10 and RTX 3060

**Comment by mklefrancois** [comment]
I cannot reproduce the issue
```
gltfr::GltfRendererElement::reloadShaders
| gltfr::RendererPathtracer::initShaders -> 217.370 ms
|-> 273.682 ms
gltfr::RendererPathtracer::createIndirectPipeline -> 2.382 ms
```

When reloading the shaders, it is loading them from two areas
* vk_gltf_renderer
* nvpro_core

Can you also reproduce it with any other scene, because it should not be related.

**Comment by tigrazone** [comment]
What about this issue? Not reallocated memory well when shader compile?
Scene use 95% of my GPU mem

**Comment by mklefrancois** [comment]
I was able to load two instances of vk_gltf_renderer with the Bistro scene. While the first one was already utilizing 90% of the memory, the second one ramped up to 98% while the first one, offloaded its memory.

The NVML monitor helps inspecting what it is going on. Nevertheless, reloading the shaders does not affect memory utilisation and it is possible to reload the shaders even in constraint situation.  

Back to my question: 

> Can you also reproduce it with any other scene, because it should not be related.

Please make sure all git repository are updated. And if this is still reproducible, please give more details on how the application was started: within Visual Studio,  after CMake install and run in the folder, etc... 


![image](https://github.com/user-attachments/assets/fe384405-b592-4cae-9c60-c514ccaafa99)
![image](https://github.com/user-attachments/assets/302f3350-7dc1-432e-9662-02d79f9d7e1b)

**Comment by tigrazone** [comment]
I find source of issue.
I change a bit shader and it is compare with very big number. Fix it and issue is gone

**Comment by mklefrancois** [comment]
Thanks for the update. Glad you found the problem in the shader code-it now makes sense why it was causing problems, and it's clear it wasn't memory or shader reloading related.

As I mentioned earlier, reloading shaders doesn't usually affect memory usage, even in constrained scenarios like the Bistro scene. After testing several scenes on my end, everything worked fine, so it appears that the issue was specifically caused by your shader modification.

That said, it would have saved time on our end if the change and its details had been shared earlier, as we spent unnecessary time investigating a bug that didn't exist. In the future, please be sure to provide enough information and double check your changes before reporting a problem.

If you experience other problems, please do not hesitate to share more details. As always, we are grateful for your reporting of any issues you may find.
