### ISSUE TITLE
strange Dielectrics implementation

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#13]
take a look at video https://youtu.be/wuCyqehFtjY
hdris is same
[gkNextRenderer](https://github.com/gameknife/gkNextRenderer) implementation taken from Blender's sources.
Is it possible to implement correct glass/dielectrics?

**Comment by mklefrancois** [comment]
There must be an interpretation in the glTF scene that isn't being propagated properly.
Would it be possible to share this scene?

**Comment by tigrazone** [comment]
taken from [here](https://sketchfab.com/3d-models/shot-glass-a9f3177d4da8486dad9d3c21e3f95830)

**Comment by tigrazone** [comment]
any dielectric MUST to look like glass. 
not just opacity or simple transmission

**Comment by mklefrancois** [comment]
I don't have permission to download the asset. Can you please add it somewhere?

**Comment by tigrazone** [comment]
[shot_glass.zip](https://drive.google.com/file/d/1nURYGYgHbWQqOzmbLFCEIyoOiFUXyie-/view?usp=sharing)

**Comment by mklefrancois** [comment]
The material contains `KHR_materials_transmission`, but uses  "alphaMode": "**BLEND**" instead of "**OPAQUE**".
Both can be used see information [here](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_transmission/README.md#blend-mode), but having it blended in this case is not recommended.

This is how it looks originally
![image](https://github.com/user-attachments/assets/b8336492-d6bb-4183-9899-f5b9c50c3130)

Now with "OPAQUE"
![image](https://github.com/user-attachments/assets/04914d72-b47f-41eb-a925-b3f496a67842)

Note that `KHR_materials_volume` wasn't used, so the glass is a thin-walled glass. Adding the volume to the material, makes it looking more like glass.
![image](https://github.com/user-attachments/assets/5fe118d7-3717-4fbb-b656-1c935804b608)

As far as I can tell, `vk_gltf_renderer` respects the various combinations of extensions. If you think it does not, please provide the reference and documentation that supports this.

* [KHR_materials_volume](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume)
* [KHR_materials_transmission](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_transmission)


Modification to the material
```
 {
      "alphaMode": "OPAQUE",
      "doubleSided": true,
      "extensions": {
        "KHR_materials_transmission": {
          "transmissionFactor": 1.0
        },
        "KHR_materials_volume": {
          "thicknessFactor": 0.1
        }
      },
```

**Comment by mklefrancois** [comment]
Sorry, I'm not sure I understand your question. 
Just to be sure, [KHR_materials_volume](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume) is part of the [Ratified Khronos Extensions](https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#ratified-khronos-extensions) and this extension is supported by the vk_gltf_renderer raytracer. There are some limitations regarding the multi-ior stack and it is expected that the camera is in the "air" medium.

**Comment by tigrazone** [comment]
Is thickness parameter of thin-walled makes sense? In sources of shaders i see only thickness==0.0 used for understand thin-walled or no

**Comment by mklefrancois** [comment]
From KHR_materials_volume

> By default, a glTF 2.0 material describes the scattering properties of a surface enclosing an infinitely thin volume. The surface defined by the mesh represents a thin wall. 

Therefore, if the `thicknessFactor == 0`, then it is thin-wall (default). Anything greater than 0.0 is consider a volume.
We are not using `thicknessTexture`, as this is computed while traversing the object, but `attenuationDistance` and `attenuationColor` are used.
