### ISSUE TITLE
renderer goes black in new build

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#19]
Scene taken [from](https://webpages.tuni.fi/vga/publications/ddish-gi-paper-scenes.zip) 
hdri also from proposed archive
folder breakfast

take a look at [video](https://youtu.be/nQ6rvXgsomU)
problem reproduced in hdri and sky modes.

**Comment by mklefrancois** [comment]
Thanks for reporting the issue.

We will be investigating the correct solution, meanwhile you can comment the following line in bsdf_function:bsdfSample()

```
data.event_type = (data.event_type & (~BSDF_EVENT_GLOSSY)) | BSDF_EVENT_IMPULSE;
```

**Comment by tigrazone** [comment]
Why it was chaged to new BSDF_EVENT_GLOSSY, BSDF_EVENT_IMPULSE ?

**Comment by NBickford-NV** [comment]
Hi @tigrazone ! A fix is on the way.

We changed the `BSDF_EVENT` names in the doc update to match McGuire et al.'s paper [*A Taxonomy of Bidirectional
Scattering Distribution Function Lobes for Rendering Engineers*](https://casual-effects.com/research/McGuire2020BSDF/McGuire2020BSDF.pdf) (there's also more documentation about what each `BSDF_EVENT` type means now). Previously, even I was getting confused about what `BSDF_EVENT_SPECULAR` meant: "does this refer to a lobe? If so, which lobes (like dielectric specular, metallic specular, and sheen) use `BSDF_EVENT_SPECULAR` and which use `BSDF_EVENT_GLOSSY`? Or maybe it refers to perfectly specular (mirror-like) reflections?" (The answer was "only the dielectric specular lobe", which isn't very useful for a renderer.)

Now, it should hopefully be clearer and matches terminology the paper's trying to standardize on -- we return `BSDF_EVENT_GLOSSY` for glossy reflections (i.e. not diffuse and not mirror-like), and return `BSDF_EVENT_IMPULSE` for mirror-like reflections (this is because the PDF and BSDF are [Dirac delta functions, a.k.a. impulse functions](https://en.wikipedia.org/wiki/Dirac_delta_function)).

That's where this bug came in! Previously, this code was what made removing `MICROFACET_MIN_ROUGHNESS` work: when we have a perfectly specular reflection, we usually get a PDF of NaN and a valid bsdf_over_pdf, so we should report a Dirac reflection. (We have this branch for NaN safety even though we use `MICROFACET_MIN_ROUGHNESS`.)

```glsl
  if(data.pdf <= 0.00001F || any(isnan(data.bsdf_over_pdf)))
  {
    data.event_type = BSDF_EVENT_ABSORB;
  }
  if(isnan(data.pdf) || isinf(data.pdf))
  {
    data.pdf = DIRAC;
  }
```

I added this line of code to try to set the event type properly: in this case, we should remove the `GLOSSY` event type and add the `IMPULSE` event type. But here's the bug - when `bsdf_over_pdf` and `pdf` are both `NaN`, we should report an event type of `BSDF_EVENT_ABSORB`, but this line of code also changes `BSDF_EVENT_ABSORB` (reject this hit) to `BSDF_EVENT_IMPULSE` (treat it as a mirror-like reflection)! As a result, the `NaN` value in `bsdf_over_pdf` makes it to the final render, slowly darkening the image.

The fix coming to nvpro_core soon is:

```diff
-  if(isnan(data.pdf) || isinf(data.pdf))
+  if((isnan(data.pdf) || isinf(data.pdf)) && data.event_type != BSDF_EVENT_ABSORB)
```

Thanks for reporting this!

**Comment by NBickford-NV** [comment]
P.S. It looks like there's another issue in how we handle this scene's tangents; we're looking into it.

**Comment by NBickford-NV** [comment]
Here's what I'm getting for what the scene looked like before the 2024-10-15 bulk change (it looks like this again with the fixed code) - does this match with what you're seeing?

![image](https://github.com/user-attachments/assets/84be90b1-f946-400a-b836-9e293a67eb55)

Note that there's a trapezoid of the left wall that renders darker than it should. Here's the scene isolated to two triangles on that wall: [breakfast-blender-2tri.zip](https://github.com/user-attachments/files/17411288/breakfast-blender-2tri.zip)

It turns out the problem here seems to be in the scene file (measurements from re-exporting with Blender). That triangle has a normal of `(00 00 80 3F, 00 00 00 00, 05 BD 78 34)`, which is `(1, 0, 2.316E-7)`, and the tangent is `(00 00 80 3F, 00 00 00 00, 00 00 00 80)`, which is `(1, 0, -0)`; these should be orthogonal, but they're nearly collinear.

Surprisingly, MikkTSpace seems to be regenerating the same tangent for this triangle when we run it (maybe because all 3 vertices of the triangle have the same UV coordinate?). So this could be due to a bug in MikkTSpace.

**Comment by tigrazone** [comment]
both walls looks strange. "recreate tangents" and "fix tangents" doesnt help me.
maybe need to fix this scene
![aa](https://github.com/user-attachments/assets/7b6bafb1-40fc-4790-b4ec-26010744d78d)
![a](https://github.com/user-attachments/assets/bd418a50-2c99-43b0-b8f3-ca2510a2239b)

but renderer before 2024-10-15 bulk change works ok

**Comment by mklefrancois** [comment]
The tangents and normals for some triangles are collinear instead of being orthogonal. The code in fix-tangent was only checking for null tangents and not for this case. Additionally, the texture coordinates for these triangles have identical values for all 3 vertices, which is invalid for MikkTSpace to recreate the tangents. In an upcoming commit, the tool to fix and recreate tangents will address these issues.

This is the result after running fix-tangents:

![image](https://github.com/user-attachments/assets/60c6f421-ca82-47a9-ad5a-bf11087975f4)

Note that saving the scene after fixing the tangents will preserve the corrected tangents.

**Comment by mklefrancois** [comment]
![bug](https://github.com/user-attachments/assets/ec3e52f9-5bb0-4189-b955-21752cfd2fc7)

**Comment by tigrazone** [comment]
This is a good news about upcoming issue fix
